### ISSUE TITLE
cssの整理

### ISSUE THREAD

**Issue by haji33** [egg-system/borderless-gym#111]
### 目的
- ページごとのrootのclassや共通のcssなど全体に関わるcssの整理

**Comment by nuno929** [comment]
@haji33 
もう少し、課題を具体化してもらうと助かります！
現状、布村が必要だと考えているのは、以下ですね。
- #118 
- #104

**Comment by haji33** [comment]
@nuno929 
> 実装イメージがあるならば

特にイメージがある訳ではないのでチームでやりやすいように決めていきたいです。

> 現状、布村が必要だと考えているのは、以下になります。

自分もヌノさんが挙げてくださった部分が課題だと思います。
あとは「classの命名規則」なども決めても良いかと思いましたが、vueではscopedになっているのでガッチリ決めなければいけないというほどではないかもしれないです。
月曜のMTGで相談させてください。

**Comment by nuno929** [comment]
本件、ある程度までは対応済みのため、一旦クローズ
※ タスクが洗い出せていないため
