### ISSUE TITLE
GymとTrainerの親modelクラスを作り、共通処理をまとめる

### ISSUE THREAD

**Issue by hk-pvt** [egg-system/borderless-gym#129]
### 目的
- 処理の共通化のため

### 背景
- 共通でまとめられる処理が、それぞれのクラスで実装されている。

### 現状の仕様
- GymとTrainerのmodelが、それぞれ独立で存在し、matching_conditions関連の処理もそれぞれ実装されている。

### 期待する仕様
- 共通処理は親クラスに実装し、GymとTrainerのmodelには独自処理のみを実装する。

**Comment by gacha1987** [comment]
@hk-pvt 
こちらユーザー処理関連のリファクタリングでGymとTrainerの親modelとして`User`クラスを実装し、masterに取り込まれていますので、共通処理を実装する場合はそちらに実装いただけると助かります 🙏

**Comment by hk-pvt** [comment]
@gacha1987 
ご対応、ご連絡ありがとうございます🙇‍♂️
承知致しました！

**Comment by nuno929** [comment]
すでにUserクラスがあるため、対応不要
