### ISSUE TITLE
ユーザー編集画面のデザイン実装（追加対応）

### ISSUE THREAD

**Issue by haji33** [egg-system/borderless-gym#144]
### 目的
トレーナーの編集画面で以下の対応をする
- 保存ボタンの色を、LPと同じにする
- フリーランスかどうかのチェックボックスを追加
- 履歴を登録できるようにする
- 休日勤務などの項目を追加する
- 希望するエリア項目を追加する

### 備考
- 前回の対応のPR：https://github.com/egg-system/borderless-gym/pull/98

**Comment by haji33** [comment]
@nuno929 
質問です！
> フリーランスかどうかのチェックボックスを追加

カンプに合わせるとしたら「現在勤めている企業」も必要でしょうか？

> 履歴を登録できるようにする

こちらは「経験企業」のことで良いでしょうか？
また、こちらの項目はカンプでは複数登録できるようになっていますが、そちらも対応しますでしょうか？

※ ↓ 参考にしているカンプ
![ユーザー編集画面のカンプ](https://user-images.githubusercontent.com/55093787/88263072-5fdb6b00-cd04-11ea-89b5-7559d2c70558.png)

**Comment by nuno929** [comment]
@haji33 
> カンプに合わせるとしたら「現在勤めている企業」も必要でしょうか？

→ 必要ですね！

> こちらは「経験企業」のことで良いでしょうか？
また、こちらの項目はカンプでは複数登録できるようになっていますが、そちらも対応しますでしょうか？

→ 複数登録必須です！

**Comment by nuno929** [comment]
この辺のDB設計は日吉さんが対応中ですね。
もう少しでマージされるかとは思います！

**Comment by haji33** [comment]
@nuno929 
ご回答ありがとうございます！承知しました。

> この辺のDB設計は日吉さんが対応中ですね。

そうでしたか😧
```
休日勤務などの項目を追加する
希望するエリア項目を追加する
```
この辺は対応してDBにもカラムを追加してしまったのですが、被ってしまったかもしれないですね…。

**Comment by nuno929** [comment]
@haji33 
日吉さん対応の項目追加がマージされたので、ご確認よろしくお願いいたします！
#130
