### ISSUE TITLE
オファー/エントリー時メール文の実装

### ISSUE THREAD

**Issue by gacha1987** [egg-system/borderless-gym#189]
### 目的
- オファー/エントリー時のメール内容をジム/オーナーで出しわけできるようにする

### 背景
- オファー/エントリー時のメール送信の本文がダミーだったので仕様に合わせた実装が必要なため

### 現状の仕様
- 未実装

### 期待する仕様
- [こちら](https://docs.google.com/spreadsheets/d/1YcXOpjeNcrsWHJjT_NakyLbr_Ymztk14X_cRI6op9xg/edit) の文面に則ってユーザー毎に送信内容を決定し、送信する仕組みの実装
- メール文面はbladeでテンプレート化する

**Comment by nuno929** [comment]
@gacha1987 
これって、reopenした理由はなんですかね？
どんな残対応がありますか？

**Comment by gacha1987** [comment]
@nuno929 
サーバー側での送信メール内容の判定処理修正(ObserverとかMailクラスの修正)がまだ未対応でして、
このissueの対応範囲の認識でしたので、reopenしました。
別issueにした方が良ければissue作成するのでcloseいただいて大丈夫です！

**Comment by nuno929** [comment]
いや、このissueで対応してもらえればと思います！

**Comment by gacha1987** [comment]
メール本文の当て込みまでこのissueで対応するのでreopen
