### ISSUE TITLE
オファー機能のリファクタリング

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#19]
## 対応内容
- 以下の指摘点に対応する
https://github.com/egg-system/borderless-gym/pull/17#discussion_r426371970

**Comment by haji33** [comment]
@nuno929 
> https://github.com/egg-system/borderless-gym/pull/17#discussion_r426371970

こちらで質問なのですが、どこのことを指摘しているのでしょうか？
`store`は使い方的に間違っていなそうでした🤔POSTの処理なのにURLパラメータでデータを送っている部分でしょうか？

**Comment by nuno929** [comment]
@haji33 
offerのfromとtoの、どちらがどちらかが全くわからない点ですね。

**Comment by haji33** [comment]
@nuno929 
> offerのfromとtoの、どちらがどちらかが全くわからない点ですね。

メソッドの中の指摘でしたか…。（レビューがついている箇所が`public function store(int $login_id, OfferRequest $request)`だったので勘違いしました🙇‍♂️）

**Comment by nuno929** [comment]
対応不要になったので、クローズ
