### ISSUE TITLE
トレーナー：オファーの一覧画面を作成

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#22]
## 対応内容
- トレーナーのマイページから、オファーを一覧で確認できるようにする
- 一覧は、以下で絞り込みできるようにする
    - 未確認
    - 承諾 / 辞退
- デフォルトでは、未確認のみ表示する
- bladeファイルは、トレーナーとジムで使いまわし可能なように作る

**Comment by natsume0718** [comment]
>一覧は、以下で絞り込みできるようにする
>未確認
>承諾 / 辞退

下記で統一します
未**返答**, 承諾, 辞退

**Comment by nuno929** [comment]
@natsume0718 
ありがとうございます！ ご対応よろしくお願いいたします。
