### ISSUE TITLE
エリアの入力を必須にしない

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#39]
### 現状の仕様
- エリアの入力が必須になっている

### 期待する仕様
- エリアの入力を任意にする

**Comment by haji33** [comment]
@nuno929 
こちらはDBの値をNullableにして対応ということでよろしいでしょうか？（デフォルト値を入れるではないと思うので）

**Comment by nuno929** [comment]
@haji33 
その認識で大丈夫です！
