### ISSUE TITLE
メールで会員登録ができない

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#58]
### 目的
- 会員登録ができない

### 現状の仕様
- 会員登録をしようとすると、エラーが発生する
    - `Class 'App\Services\Trainer' not found`

### 期待する仕様
- 会員登録できるように修正する

**Comment by natsume0718** [comment]
お疲れさまです  

上記についてmasterで登録実施してみたところ問題なく動作しました  
キャッシュが残っている状態かとおもったのですが
キャッシュクリアと、クラスマップ再生成は実行済みでしょうか

`App\Services\Trainer`  を検索してもヒットするものがなかったので
キャッシュ系だと思いますので再度実施してみていただけると助かります

**Comment by nuno929** [comment]
@natsume0718 
マスターが最新になっていなかったようです。
すでに修正済みのエラーみたいですね。ご確認ありがとうございました。
