### ISSUE TITLE
オファーの整理

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#61]
### 目的
- 大幅に仕様が変更になったため

### 背景
- マネタイズポイントが変わったため、オファーの使用も変更になる

### 現状の仕様
- いきなり返答待ちになる

### 期待する仕様
- オファーの状態は以下になる
- 以下にあわせたルートを実装する
- オファー周りの実装をリファクタリングして、MatchingServiceに集約する

#### 状態遷移表

|状態|説明|遷移経路|
|--|--|--|
|エントリー|一番はじめの状態。チャットを始めるタイミングで追加される。状態名は、ジムオーナーの場合はオファー、トレーナーからの場合はエントリーになる|状態なし|
|選考|選考中の段階。チャットや対面でのやり取りをしている状態|状態なし → 選考|
|正式依頼|ジムオーナーから、トレーナーに依頼している状態|選考 → 正式依頼|
|辞退|トレーナーが正式依頼に対して、辞退した状態|正式依頼 → 辞退|
|成約|トレーナーが正式依頼に対して、承諾した状態|正式依頼 → 承諾|

**Comment by gacha1987** [comment]
選考はなくす
エントリーもサービスとしては不要だが、初回登録時のデフォルト値として定義する

**Comment by gacha1987** [comment]
|状態|遷移可能アクター |処理概要|
|--|--|--|
|初期状態(エントリー or オファー)|トレーナー、ジムオーナー|offersに初期登録を行い、toのuserへメール送信(toがトレーナー、ジムオーナーかで文面変える)|
|正式依頼|ジムオーナーのみ|状態を`正式依頼`に更新し、トレーナーへメール送信|
|成約|トレーナーのみ態|状態を`成約`に更新し、ジムオーナーへメール送信|
|辞退|トレーナーのみ|状態を`辞退`に更新し、ジムオーナーへメール送信|

**Comment by gacha1987** [comment]
このissueでの対応リスト

- [ ] 状態登録処理実装(バックエンド)
- [ ] 状態遷移時のメール送信実装(バックエンド)
- [ ] エントリー/オファー一覧画面(バックエンド)
- [ ] エントリー/オファー一覧画面(フロントエンド)

現状緒方が把握できてない箇所
- 状態登録後の遷移先(個別のチャット画面への遷移かなと思いつつチャット機能の詳細が把握し切れておらずどこへ遷移すればいいか把握し切れていない)
- メール本文

**Comment by nuno929** [comment]
対応完了後
- メール文の実装
- オファー一覧の画面コーディング
    - 難易度は低い

**Comment by nuno929** [comment]
仕様がFIXしているわけではないので、テスト実装は後回しでもいい

**Comment by nuno929** [comment]
@gacha1987 
以下について、issueを作成していただければ、助かります！

> メール文の実装
オファー一覧の画面コーディング
オファー/エントリー後のFBデザイン実装
