### ISSUE TITLE
【日吉さん】検索機能の整理

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#62]
### 目的
- 検索機能が粗雑になっている

### 背景
- ジムオーナーとトレーナーでできる機能がほとんど同じ

### 現状の仕様
- 検索がコントローラにベタ書きになっている

### 期待する仕様
- 検索周りの処理をSerachServiceに集約する

### 1. 共通機能
1-1. 検索機能（サービスクラス）の整理
→ PR #151 で対応中（ヌノさんレビュー中）

### 2. ジム一覧画面
2-1. フロントエンド
2-1-1. 全件表示
2-1-2. ページネーション処理
2-1-3. 検索フォーム
2-1-4. デザインFB対応

2-2. バックエンド(フロント以外)
2-2-1. コントローラ
2-2-2. Request修正（バリデーション含む）
2-2-3. マスタ修正（デザインカンプを元にマスタの項目修正）
2-2-4. テスト実装
・ルートレベルのテスト
・検索サービスクラスの単体テスト

**Comment by nuno929** [comment]
- 検索用インターフェースを作る
- 共通の検索処理をまとめる
    - 差分は個別のモデル内で吸収する
- 検索処理の呼び出しは、SerchServiceにまとめる

**Comment by nuno929** [comment]
余力があれば、検索項目を仕様書どおりにまとめる

**Comment by hk-pvt** [comment]
- SearchInterfaceの実装にあたって、gym or trainerのsearchクラスをDIするための手段
1. facadeで分岐させる。
2. マジックメソッドで分岐させる。
3. executerを使用する。

- requestクラスに、search用のinterfaceを持たせる。(searchParamはリクエスト側に持たせる）
- SearchServiceは独立した存在にする。
- Components → Serviceに移動。

**Comment by nuno929** [comment]
- 一旦、バックのみ
     - 今週中

**Comment by hk-pvt** [comment]
本issueでの対応リスト

### バックエンド
- [ ] 検索機能の実装
→ PR #151 で対応中（ヌノさんレビュー中）

### フロントエンド
- [ ] 初期画面（条件を絞って検索も含む）
→ 未対応(上記バックエンドの対応後 or 巻き取って頂く)

**Comment by nuno929** [comment]
@hk-pvt 
確認したい点がいまいちわからず...
粒度もこれでいいんでしょうか？ 一応はあっていますが...

**Comment by hk-pvt** [comment]
@nuno929 
> 確認したい点がいまいちわからず...
説明不足ですみません。
やりたいことは、このIssueでのスコープ確認と現状の共有（整理）ですね。
また先日のMTGの際、「リリース前で時間も無いので作業を巻き取るかも」ってことだったので、そこも含めてどこを私が対応するのかなどの相談がしたかったです。

> 粒度もこれでいいんでしょうか？ 一応はあっていますが...
粒度を修正しましたが、これで相談可能でしょうか？
認識と違ってましたら、お手数ですがご指摘ください。

**Comment by nuno929** [comment]
@hk-pvt 
> やりたいことは、このIssueでのスコープ確認と現状の共有（整理）ですね。

→ 布村の感覚だと、スコープは以下になります。確認するなら、もう少し細かい説明をしてもらえますか？
また、巻き取るかどうかの相談なのに、どこまで対応できるかがないのが気になりますね...

- 検索のサービスクラスの実装
    -  #151 でレビュー中
- ジム一覧画面の実装
    - 全件を表示可能にする
    - ペジネーション処理の実装
- 検索フォームの実装
    - コントローラやrequestの修正対応も含む
- マスタの修正
    - デザインカンプにあわせて、マスタを修正する
- テストの実装
    - ルートレベルでのテストを実装する
    - 検索サービスクラスの単体テストを実装する
- デザインFB対応
    - 実際のデザインの対応を実施する

**Comment by hk-pvt** [comment]
@nuno929 
> → 布村の感覚だと、スコープは以下になります。確認するなら、もう少し細かい説明をしてもらえますか？

スコープの共有ありがとうございます。また確認の粒度が雑で失礼しました。
上記を参考に、本Issueの概要の部分に記載しておきました。

> また、巻き取るかどうかの相談なのに、日程やどこまで対応できるかがないのが気になりますね...

日程については、レビュー依頼中のPRのフィードバック量や、スコープの範囲など認識合わせてからじゃないと出せないので、その後と思ってましたが、それもお伝えすべきでした。失礼しました。

---------

日程や、どこまで対応できるかについてですが、
以下は、8/10(月)までに対応できるようにします（FB等で少し足が出る可能性はありますが）
> 1-1. 検索機能（サービスクラス）の整理
> 2-1. 全件表示
> 2-4. マスタ修正（デザインカンプを元にマスタの項目修正）

また以下の対応については、8/11(火)〜になってしまいます...
> 2-2. ページネーション処理実装
> 2-3. 検索フォーム実装（コントローラ、Request修正含む）
> 2-5. テスト実装
> ・ルートレベルのテスト
> ・検索サービスクラスの単体テスト
> 2-6. デザインFB対応

**Comment by nuno929** [comment]
>以下は巻き取っていただけますでしょうか。

> >2-1. フロントエンド
2-1-1. 全件表示
2-1-2. ページネーション処理
2-1-3. 検索フォーム
2-1-4. デザインFB対応

→ 承知いたしました！
