### ISSUE TITLE
トレーナー一覧の検索機能の作成

### ISSUE THREAD

**Issue by nuno929** [egg-system/borderless-gym#8]
### 要件
- ジムオーナーでログイン後に、トレーナー検索できるようにする

### 対応内容
- ログイン画面の作成
    - トレーナー用とジムオーナー用の二種類
    - ログインできるようにする
- ジムオーナーのログイン後のページを作成
    - ダッシュボード画面のようなものを用意する
        - 一旦は、ページさえあればOK
    - サイドメニューでトレーナー一覧へのリンクがあればいい
        - ジムオーナーは、PCファーストの想定
- トレーナー一覧
    - トレーナーの一覧を表示する
    - 検索項目は以下。表示内容も一旦は以下でOK
        - 種類（パーソナル、ボクシング、フィットネス、etc）
        - 場所／エリア
        - 単価
        - 働ける曜日や時間帯
    - 後々は、トレーナーのジム一覧と共通化する構想あり

**Comment by natsume0718** [comment]
以下について仕様を教えていただきたいです

 - ログインの方法→登録時にパスワードを入力する式じゃないのでユーザがパスワードを得る方法
 - ログインに使う項目(email?)

#9 の内容全般
検索項目をDBから取得して表示するのを共通化するということをおっしゃている感じでしょうか？
>matcing_conditonsに移行した項目は、元のテーブルから削除する
どういった挙動を想定しているのかわからないので教えていただきたいです
