### ISSUE TITLE
トレーナー登録時に既に登録済みだった場合の挙動修正

### ISSUE THREAD

**Issue by gacha1987** [egg-system/borderless-gym#95]
### 目的
- UX向上のため

### 背景
- 現在、トレーナー登録時に既に登録済みだった場合はTOP(LP)へリダイレクトされるが、UX的によろしくないので修正する

### 現状の仕様
- トレーナー登録時に既に登録済みだった場合はTOP(LP)へリダイレクトする

### 期待する仕様
- 入力画面に戻って「既に登録されているユーザーです」的なメッセージを表示する 🤔

**Comment by nuno929** [comment]
@gacha1987 
トップ画面へのリダイレクトよりも、ログイン画面とかの方がUX的には良さそうな気がします。

**Comment by gacha1987** [comment]
@nuno929 
そうですね！エラーメッセージも書いては見たものの登録画面に戻しても意味ないのでログイン画面の方が良い気がします。
そちらで修正します。
